# Generated by Django 3.2.7 on 2021-09-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('esVisible', models.BooleanField()),
                ('rutaFoto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LocalComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('tittle', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField()),
                ('link', models.CharField(max_length=500)),
                ('horarioAtencion', models.TextField()),
                ('tieneDelivery', models.BooleanField()),
                ('estado', models.CharField(max_length=250)),
                ('privateKeyMercadopago', models.TextField()),
                ('publicKeyMercadopago', models.TextField()),
                ('tieneMercadopago', models.BooleanField()),
                ('rutaLogo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('tipoEntrega', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('datosEntrega', models.TextField()),
                ('refLocalComercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication_back.localcomercial')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('total', models.IntegerField()),
                ('tipoPago', models.CharField(max_length=250)),
                ('refLocalComercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication_back.localcomercial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('refVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication_back.venta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('notaEspecial', models.TextField()),
                ('refOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication_back.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('precioActual', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('esVisible', models.BooleanField()),
                ('rutaFoto', models.CharField(max_length=250)),
                ('refCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication_back.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='refLocalComercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication_back.localcomercial'),
        ),
    ]
